import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireEditor } from '../../../../lib/editor-auth';
import { adminDb } from '../../../../lib/supabase';
import { addGraduate, addPage, deletePage, updatePage, updateYearbook } from '../../actions';
import { movePage, publishGraduateAsset, uploadGraduateAsset, uploadYearbookCover } from '../../assets-actions';

export default async function EditYearbookPage({params}:{params:Promise<{id:string}>}){
  await requireEditor();
  const {id}=await params;
  const db=adminDb();
  const [{data:book},{data:pages},{data:graduates}]=await Promise.all([
    db.from('yearbooks').select('*').eq('id',id).maybeSingle(),
    db.from('yearbook_pages').select('*').eq('yearbook_id',id).order('page_number'),
    db.from('graduates').select('*').eq('yearbook_id',id).order('display_order',{ascending:true,nullsFirst:false}).order('created_at')
  ]);
  if(!book) notFound();
  return <main className="admin-shell"><header className="admin-top"><div><Link href="/admin" className="back-link">← Yearbook Library</Link><div className="eyebrow">HBIU Graduation Yearbook Studio</div><h1>{book.title}</h1></div><div className="status-pill">{book.status}</div></header>
    <section className="admin-panel"><h2>Yearbook Settings</h2><form action={updateYearbook} className="settings-grid"><input type="hidden" name="yearbook_id" value={book.id}/><label>Title<input name="title" defaultValue={book.title} required/></label><label>Subtitle<input name="subtitle" defaultValue={book.subtitle||''}/></label><label>Year<input name="year" type="number" defaultValue={book.year} required/></label><label>Status<select name="status" defaultValue={book.status}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><button className="gold-button">Save Yearbook</button></form><form action={uploadYearbookCover} className="asset-upload-row"><input type="hidden" name="yearbook_id" value={book.id}/><label>Yearbook cover image<input name="cover" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" required/></label><button className="small-button">Upload Cover</button>{book.cover_image_path&&<span className="muted">Cover asset attached</span>}</form></section>

    <section className="admin-panel"><div className="section-head"><div><h2>Pages</h2><p>Add, edit, reorder or remove pages. The page sequence is preserved separately for every duplicated yearbook.</p></div><form action={addPage}><input type="hidden" name="yearbook_id" value={book.id}/><button className="gold-button">+ Add Page</button></form></div>
      <div className="page-editor-list">{(pages||[]).map((p:any)=><article key={p.id} className="page-editor-card"><div><div className="page-chip">{p.page_number}</div><div className="page-order-buttons"><form action={movePage}><input type="hidden" name="page_id" value={p.id}/><input type="hidden" name="yearbook_id" value={book.id}/><button name="direction" value="up">↑</button><button name="direction" value="down">↓</button></form></div></div><form action={updatePage} className="page-edit-form"><input type="hidden" name="page_id" value={p.id}/><input type="hidden" name="yearbook_id" value={book.id}/><div className="form-row"><label>Page title<input name="title" defaultValue={p.title||''}/></label><label>Page type<input name="page_type" defaultValue={p.page_type}/></label><label>Layout<select name="layout_key" defaultValue={p.layout_key||'classic'}><option value="classic">Classic Cream</option><option value="navy">Navy & Gold</option><option value="gallery">Graduate Gallery</option><option value="message">Leadership Message</option><option value="program">Commencement Program</option></select></label></div><label>Editable page text<textarea name="body" rows={5} defaultValue={p.content?.body||p.content?.text||p.content?.description||''}/></label><div className="form-actions"><button className="small-button">Save Page</button></div></form><form action={deletePage}><input type="hidden" name="page_id" value={p.id}/><input type="hidden" name="yearbook_id" value={book.id}/><button className="danger-link">Remove</button></form></article>)}</div>
    </section>

    <section className="admin-panel"><div className="section-head"><div><h2>Graduate Gallery</h2><p>Add graduate records, professional photos and individual graduation flyers.</p></div></div><form action={addGraduate} className="graduate-form"><input type="hidden" name="yearbook_id" value={book.id}/><input name="full_name" placeholder="Graduate full name" required/><input name="credential" placeholder="Credential / Degree"/><input name="program_title" placeholder="Program title"/><input name="college_name" placeholder="College"/><input name="honors" placeholder="Honors / recognition"/><button className="gold-button">Add Graduate</button></form>
      <div className="graduate-list">{(graduates||[]).map((g:any)=><div key={g.id} className="graduate-row graduate-row-expanded"><div className="graduate-avatar">{g.full_name.split(/\s+/).slice(0,2).map((x:string)=>x[0]).join('')}</div><div className="graduate-info"><strong>{g.full_name}</strong><span>{[g.credential,g.program_title,g.college_name].filter(Boolean).join(' • ')||'Graduate record'}</span><small>{g.published?'Published':'Draft graduate record'}</small></div><div className="graduate-assets"><form action={uploadGraduateAsset}><input type="hidden" name="yearbook_id" value={book.id}/><input type="hidden" name="graduate_id" value={g.id}/><input type="hidden" name="asset_type" value="photo"/><input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" required/><button className="small-button">Upload Photo</button></form><form action={uploadGraduateAsset}><input type="hidden" name="yearbook_id" value={book.id}/><input type="hidden" name="graduate_id" value={g.id}/><input type="hidden" name="asset_type" value="flyer"/><input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf" required/><button className="small-button">Upload Flyer</button></form>{(g.photo_path||g.flyer_path)&&<form action={publishGraduateAsset}><input type="hidden" name="yearbook_id" value={book.id}/><input type="hidden" name="graduate_id" value={g.id}/><button className="gold-button">Publish Graduate Assets</button></form>}</div></div>)}{!graduates?.length&&<p className="muted">No graduate records added yet.</p>}</div>
    </section>
  </main>;
}
